#include <stdio.h>
#include <math.h>

/*
Triangle numbers are generated by adding natural numbers: 
T_n = 1 + 2 + 3 + ... + n = n(n+1)/2
Instead of using brute force divisor counting (which is extremely slow),
we use the mathematical formula for counting divisors based on prime factorization:
Any integer N can be expressed as: N = p1^a1 * p2^a2 * p3^a3 * ...
where pn are distinct prime numbers and an are their exponents.
The number of divisors D(N) is then: D(N) = (a1+1) * (a2+1) * (a3+1) * ...
For example: 28 = 2^2 * 7^1, so D(28) = (2+1)*(1+1) = 3*2 = 6 divisors.
We generate triangle numbers sequentially and factorize each one using a precomputed
list of primes to efficiently count the number of divisors.
 */

#define MAX_PRIMES 10000
#define TARGET_DIVISORS 500

int primes[MAX_PRIMES];
int prime_count = 0;

// Generate primes up to limit using Sieve of Eratosthenes
void generate_primes(int limit) {
    char is_prime[limit + 1];
    for (int i = 0; i <= limit; i++) is_prime[i] = 1;
    is_prime[0] = is_prime[1] = 0;
    
    for (int i = 2; i * i <= limit; i++) {
        if (is_prime[i]) {
            for (int j = i * i; j <= limit; j += i) {
                is_prime[j] = 0;
            }
        }
    }
    
    for (int i = 2; i <= limit; i++) {
        if (is_prime[i]) {
            primes[prime_count++] = i;
        }
    }
}

// Count divisors using prime factorization
int count_divisors(int n) {
    int divisors = 1;
    int temp = n;
    
    for (int i = 0; i < prime_count && primes[i] * primes[i] <= temp; i++) {
        if (temp % primes[i] == 0) {
            int exponent = 0;
            while (temp % primes[i] == 0) {
                exponent++;
                temp /= primes[i];
            }
            divisors *= (exponent + 1);
        }
    }
    
    if (temp > 1) {
        divisors *= 2; // Remaining factor is a prime
    }
    
    return divisors;
}

int main() {
    // Generate primes up to 65500 (sufficient for triangle numbers within 32-bit integers)
    generate_primes(65500);
    
    int n = 1;
    int triangle = 0;
    int divisors = 0;
    
    while (divisors <= TARGET_DIVISORS) {
        triangle += n; // triangle = n(n+1)/2
        divisors = count_divisors(triangle);
        n++;
    }
    
    printf("The first triangle number with over %d divisors is: %d\n", TARGET_DIVISORS, triangle);
    printf("It is the %dth triangle number with %d divisors\n", n-1, divisors);
    
    return 0;
}